# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- develop
- features/*

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  buildConfiguration: 'Release'

steps:
- bash: >
    shopt -s globsta;
    for d in **/*.csproj; do
      echo "Building directory $d"; 
      dotnet build $d -c $(buildConfiguration)
    done;
  displayName: 'dotnet build $(buildConfiguration)'
  continueOnError: true
