# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- develop
- features/*

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  buildConfiguration: 'Release'

steps:
- bash: >
    find . -name '*.csproj' -print0 | 
    while IFS= read -r -d $'\0' line; do
        echo "Building directory $line";
        echo "Building directory parent $(dirname "$dir")"; 
        echo $(Build.SourcesDirectory)
        # dotnet restore $line --packages $(Build.SourcesDirectory)/lifebook-nuget-feed/** 
        # -s https://api.nuget.org/v3/index.json
        # dotnet restore -s $(Build.SourcesDirectory)/lifebook-nuget-feed
        dotnet build $line --source $(Build.SourcesDirectory)/lifebook-nuget-feed --source https://api.nuget.org/v3/index.json -c $(buildConfiguration)
    done
  displayName: 'dotnet build $(buildConfiguration)'
  continueOnError: true
